version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: supa-chat-api
    ports:
      - "8001:8001"
    volumes:
      - ../.env:/app/.env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1 
    networks:
      - crawl-network
    security_opt:
      - no-new-privileges

  explorer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: supa-explorer
    ports:
      - "8501:8501"
    volumes:
      - ../.env:/app/.env
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app/supabase_explorer
    command: streamlit run supabase_explorer.py --server.address=0.0.0.0
    networks:
      - crawl-network
    security_opt:
      - no-new-privileges

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    container_name: supa-chat-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:8001
      - NODE_ENV=development
      - DOCKER_ENV=true
    volumes:
      - ../frontend:/app
      - /app/node_modules
    networks:
      - crawl-network
    security_opt:
      - no-new-privileges
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  crawl-network:
    driver: bridge
      